apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
  namespace: default
spec:
  containers:
  - name: command-demo-container
    image: debian
    command: ["printenv"]
    arg: ["HOSTNAME", "KUBERNETES_PORT"]
  restartPolicy: OnFailure