apiVersion: v1
kind: Pod
metadata:
  name: my-pod

spec:
  containers:
    - image: nginx
      name:  my-app
      volumeMounts:
        - mountPath: /test-pd
          name: test-volume
  volumes:
    - name: test-volume
      hostPath:
        path: /usr/local
        type: Directory
  