apiVersion: apps/v1
kind: Deployment
metadata:
  name:  redis-deployment
  labels:
    app:  redis
spec:
  replicas: 10
  selector:
    matchLabels:
      app: redis

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 4
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis-container
        image: redis:7.0