apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-job
spec:
  template:
    metadata:
      name: countdown-pod
    spec:
      containers:
        - name: counter
          image: centos:alpine
          command:
            - "/bin/bash"
            - "-c"
            - "for i in 9 8 7 6 5 4 3 2 1 ; do each $i ; sleep 2 ; done"  
      restartPolicy: Never
