apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-test-ttl
  namespace: default
spec:
  schedule: "*/1 * * * *"
  ttlSecondsAfterFinished: 10
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-test
            image: busybox
            args: ['/bin/sh', '-c', 'date; echo Hello from the Kubernetes cluster']
          restartPolicy: OnFailure